# Synapse-managed Shopify App
# Merchant: cdaac269-9d01-4104-99d9-ebcfeaa7da0c
# Generated: 2025-11-07T03:26:35.814Z

name = "Synapse Extensions"
client_id = "8e2b2a774e4c8e4381c784e110d80111"
application_url = "https://shopify.dev"
embedded = true

[auth]
redirect_urls = [
  "https://shopify.dev/auth/callback",
  "https://localhost/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
dev_store_url = "feature-test-2.myshopify.com"

[access_scopes]
use_legacy_install_flow = true
scopes = "read_products,write_products,read_orders,write_orders"

[webhooks]
api_version = "2024-10"
