[package]
name = "free_shipping_over_50"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/run.rs"

[dependencies]
shopify_function = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
lto = true
opt-level = "z"
strip = true
